export const GET_CART_REQUEST = "REQUEST_CART_DATA";
export const GET_CART_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_DATA_FAILURE";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAILED = "REMOVE_CART_ITEM_FAILED";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILED = "UPDATE_CART_FAILED";
