export const GET_CART_REQUEST = "REQUEST_CART_DATA";
export const GET_CART_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_DATA_FAILURE";


// export const GET_CART_DATA_REQUEST="GET_CART_DATA_REQUEST";
// export const GET_CART_DATA_SUCCESS="GET_CART_DATA_SUCCESS";
// export const GET_CART_DATA_FAILURE="GET_CART_DATA_FAILURE";
